Repository confidential-containers/cloud-api-adaptor, pull requests merged in 2024-07, with the labels that each got.

#1908 libvirt: Bump to kcli 99.0.202407031308
  src/cloud-api-adaptor/versions.yaml
Labels: test_e2e_libvirt

#1914 ibmcloud: revise ibmcloud README
  src/cloud-api-adaptor/ibmcloud/README.md
  src/cloud-providers/ibmcloud/provider.go
Labels: test_e2e_libvirt

#1891 versions: add entry for CoCo operator
  docs/Release-Process.md
  src/cloud-api-adaptor/Makefile
  src/cloud-api-adaptor/Makefile.defaults
  src/cloud-api-adaptor/install/README.md
  src/cloud-api-adaptor/test/provisioner/provision.go
  src/cloud-api-adaptor/test/utils/versions.go
  src/cloud-api-adaptor/versions.yaml
Labels: test_e2e_libvirt

#1918 test/e2e: Skip unstable libvirt test
  src/cloud-api-adaptor/test/e2e/libvirt_test.go
Labels: e2e-test

#1917 doc: Release doc updates
  docs/Release-Process.md
  hack/release-helper.sh
Labels: documentation, release

#1933 auth: allow specifying auth.json for guest-pull
  src/cloud-api-adaptor/cmd/process-user-data/main.go
  src/cloud-api-adaptor/docs/registries-authentication.md
  src/cloud-api-adaptor/ibmcloud-powervs/image/copy-files.sh
  src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
  src/cloud-api-adaptor/pkg/agent/config.go
  src/cloud-api-adaptor/pkg/agent/config_test.go
  src/cloud-api-adaptor/pkg/userdata/provision.go
  src/cloud-api-adaptor/pkg/userdata/provision_test.go
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/kata-agent.service.d/10-override.conf
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/tmpfiles.d/peerpods.conf
  src/cloud-api-adaptor/podvm/files/etc/agent-config.toml
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.service
  src/cloud-api-adaptor/podvm/qcow2/copy-files.sh
  src/cloud-providers/util/cloudinit/cloudconfig.go
  src/cloud-providers/util/cloudinit/cloudconfig_test.go
Labels: test_e2e_libvirt

#1939 podvm-mkosi: update podvm-builder for fedora image
  src/cloud-api-adaptor/ibmcloud-powervs/image/prereq.sh
  src/cloud-api-adaptor/podvm-mkosi/Makefile
  src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder
  src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.fedora
  src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.rhel
  src/cloud-api-adaptor/podvm/README.md
Labels: test_e2e_libvirt

#1941 process-user-data: Fix the assignment of config filenames
  src/cloud-api-adaptor/pkg/userdata/provision.go
Labels: test_e2e_libvirt

#1944 release: Update go modules for another pre-release
  src/cloud-api-adaptor/go.mod
  src/csi-wrapper/go.mod
  src/peerpod-ctrl/go.mod
Labels: test_e2e_libvirt

#1850 cloud-config: streamline credentials provisioning
  src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
  src/cloud-api-adaptor/pkg/forwarder/forwarder.go
  src/cloud-api-adaptor/pkg/userdata/provision.go
  src/cloud-api-adaptor/pkg/userdata/provision_test.go
Labels: core
