Repository confidential-containers/cloud-api-adaptor, pull requests merged in 2024-06, with the labels that each got.

#1858 podvm: launch guest-components as systemd units
  src/cloud-api-adaptor/pkg/agent/test-data/sample-agent-config.toml
  src/cloud-api-adaptor/pkg/agent/update.go
  src/cloud-api-adaptor/pkg/agent/update_test.go
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton-debug/usr/lib/systemd/system/api-server-rest.service.d/20-debug.conf
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton-debug/usr/lib/systemd/system/attestation-agent.service.d/20-debug.conf
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton-debug/usr/lib/systemd/system/confidential-data-hub.service.d/20-debug.conf
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system-preset/30-coco.preset
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/attestation-agent.service.d/10-override.conf
  src/cloud-api-adaptor/podvm/files/etc/agent-config.toml
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/attestation-agent.service
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/confidential-data-hub.path
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/confidential-data-hub.service
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.service
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/multi-user.target.wants/attestation-agent.service
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/multi-user.target.wants/confidential-data-hub.path
  src/cloud-api-adaptor/versions.yaml
Labels: test_e2e_libvirt

#1861 test/e2e: Skip all libvirt env tests
  src/cloud-api-adaptor/test/e2e/libvirt_test.go
Labels: RFC, test_e2e_libvirt

#1864 versions: Bump golang-fedora image version
  src/cloud-api-adaptor/Dockerfile
  src/cloud-api-adaptor/docs/addnewprovider.md
  src/csi-wrapper/Dockerfile.csi_wrappers
  src/peerpod-ctrl/Dockerfile
Labels: test_e2e_libvirt

#1865 guest-components: Bump guest-components dependency
  .github/workflows/azure-podvm-image-build.yml
  .github/workflows/podvm_binaries.yaml
  src/cloud-api-adaptor/Makefile
  src/cloud-api-adaptor/azure/build-image.md
  src/cloud-api-adaptor/docker/image/Makefile
  src/cloud-api-adaptor/libvirt/kcli_cluster.sh
  src/cloud-api-adaptor/podvm-mkosi/Makefile
  src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries
  src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries.fedora
  src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries.rhel
  src/cloud-api-adaptor/podvm/Makefile.inc
  src/cloud-api-adaptor/test/e2e/README.md
  src/cloud-api-adaptor/test/e2e/common.go
  src/cloud-api-adaptor/test/e2e/common_suite.go
  src/cloud-api-adaptor/versions.yaml
Labels: dependencies, test_e2e_libvirt

#1872 versions: Update the kata versions to 3.6.0
  src/cloud-api-adaptor/go.mod
  src/cloud-api-adaptor/go.sum
  src/cloud-api-adaptor/versions.yaml
  src/csi-wrapper/go.mod
  src/csi-wrapper/go.sum
Labels: test_e2e_libvirt

#1869 podvm: Remove OPA from build
  .gitignore
  src/cloud-api-adaptor/Makefile.defaults
  src/cloud-api-adaptor/docker/image/Dockerfile
  src/cloud-api-adaptor/docs/policy.md
  src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system-preset/30-coco.preset
  src/cloud-api-adaptor/podvm/Makefile.inc
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-opa.service
  src/cloud-api-adaptor/versions.yaml
Labels: test_e2e_libvirt

#1885 doc: Remove references to `CCv0`
  README.md
  docs/architecture.md
  src/cloud-api-adaptor/README.md
  src/cloud-api-adaptor/docs/DEVELOPMENT.md
  src/cloud-api-adaptor/docs/tls-proxy-forwarder.md
  src/cloud-api-adaptor/ibmcloud-powervs/README.md
  src/cloud-api-adaptor/podvm/README.md
Labels: documentation

#1871 doc: Release process
  docs/Release-Process.md
Labels: documentation
