Repository confidential-containers/cloud-api-adaptor, pull requests merged in 2024-10, with the labels that each got.

#2078 podvm: Make download-image.sh always pull
  src/cloud-api-adaptor/podvm/hack/download-image.sh
Labels: test_e2e_libvirt

#2082 Revert upload artifacts bump
  .github/workflows/caa_build_and_push_per_arch.yaml
Labels: test_e2e_libvirt

#2067 APF: Rename KataAgentNamespace
  src/cloud-api-adaptor/cmd/agent-protocol-forwarder/main.go
  src/cloud-api-adaptor/docs/SecureComms.md
  src/cloud-api-adaptor/pkg/forwarder/forwarder.go
  src/cloud-api-adaptor/podvm/files/etc/systemd/system/agent-protocol-forwarder.service
Labels: test_e2e_libvirt

#2088 CI: adjust azure nightly workflow for actions/upload-artifact@4
  .github/workflows/azure-e2e-test.yml
Labels: CI, provider/azure

#2064 azure: switch nightly podvm to mkosi-based image
  .github/workflows/azure-podvm-image-build.yml
Labels: provider/azure, podvm

#2091 checklinks: add link to exclude
  .lycheeignore
Labels: CI

#2098 ci: fix azure nightly mkosi build
  .github/workflows/azure-podvm-image-build.yml
Labels: CI, provider/azure

#2077 kbs: Remove oci.kbs version and references
  .github/workflows/azure-e2e-test.yml
  .github/workflows/e2e_libvirt.yaml
  src/cloud-api-adaptor/libvirt/config_libvirt.sh
  src/cloud-api-adaptor/test/e2e/README.md
  src/cloud-api-adaptor/test/e2e/main_test.go
  src/cloud-api-adaptor/test/provisioner/azure/provision_azure.properties
  src/cloud-api-adaptor/test/provisioner/azure/provision_azure_cli_auth.properties
  src/cloud-api-adaptor/test/provisioner/azure/provision_common.go
  src/cloud-api-adaptor/test/provisioner/azure/provision_initializer.go
  src/cloud-api-adaptor/test/provisioner/docker/provision_common.go
  src/cloud-api-adaptor/test/provisioner/docker/provision_docker.properties
  src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
  src/cloud-api-adaptor/test/provisioner/trustee_kbs.go
  src/cloud-api-adaptor/test/tools/provisioner-cli/main.go
  src/cloud-api-adaptor/versions.yaml
Labels: test_e2e_libvirt

#2102 ci: fix passing of image-id to e2e test
  .github/workflows/azure-podvm-image-build.yml
Labels: CI, provider/azure

#2080 caa: fixing toolchain not available
  src/cloud-api-adaptor/go.mod
  src/cloud-api-adaptor/podvm/go.mod
  src/cloud-providers/go.mod
  src/csi-wrapper/go.mod
  src/peerpod-ctrl/go.mod
  src/webhook/go.mod
Labels: test_e2e_libvirt

#2129 workflows: Cancel previous jobs if PR/branch is updated
  .github/workflows/azure-e2e-test.yml
  .github/workflows/azure-nightly-build.yml
  .github/workflows/azure-podvm-image-build.yml
  .github/workflows/build-golang-fedora.yaml
  .github/workflows/build.yaml
  .github/workflows/commit-message-check.yaml
  .github/workflows/daily-e2e-tests-ibmcloud.yaml
  .github/workflows/daily-e2e-tests-libvirt.yaml
  .github/workflows/e2e_on_pull.yaml
  .github/workflows/links.yml
  .github/workflows/lint.yaml
  .github/workflows/publish_images_on_push.yaml
Labels: CI

#2134 workflow: Switch libvirt e2e test to gh-runnner
  .github/workflows/e2e_libvirt.yaml
Labels: e2e-test

#2136 versions: Bump golang-fedora image version
  src/cloud-api-adaptor/Dockerfile
  src/cloud-api-adaptor/docs/addnewprovider.md
  src/csi-wrapper/Dockerfile.csi_wrappers
  src/peerpod-ctrl/Dockerfile
Labels: test_e2e_libvirt
